apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: redis-example
  name: redis-example
spec:
  ports:
  - port: 6379
    targetPort: redis-port
  selector:
    app: redis-example
  type: NodePort
