apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: deploy-grpc-example
    tier: backend
    environment: development
  name: grpc-example
spec:
  ports:
  - port: 1313
    targetPort: app-port
  selector:
    app: deploy-grpc-example
